version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-chat
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-dbs.sql:/docker-entrypoint-initdb.d/init-dbs.sql

  redis:
    image: redis:7-alpine
    container_name: redis-chat
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:6
    container_name: mongo-chat
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio-chat
    restart: always
    command: ["minio", "server", "/data", "--console-address", ":9001"]
    ports:
      - "9000:9000"  
      - "9001:9001"   
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-chat
    restart: always
    command: >
      sh -c "rabbitmq-plugins enable --offline rabbitmq_stomp && rabbitmq-server"
    ports:
      - "5672:5672"   
      - "61613:61613" 
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  redis_data:
  mongo_data:
  minio_data:
  rabbitmq_data:
