apiVersion: v1
kind: ConfigMap
metadata:
  name: arch-chat-config
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  MONGO_HOST: "mongo-service"
  MONGO_PORT: "27017"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_RELAY_HOST: "rabbitmq-service"
  RABBITMQ_RELAY_PORT: "61613"
  MINIO_ENDPOINT: "http://minio-service:9000"
  USER_SERVICE_URL: "http://user-service:8081"
  MESSAGING_SERVICE_URL: "http://messaging-service:8082"
  MESSAGING_WS_URL: "ws://messaging-service:8082"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8083"
  CALLING_WS_URL: "ws://calling-service:8084"

---
apiVersion: v1
kind: Secret
metadata:
  name: arch-chat-secrets
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgrespassword"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guestpassword"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "miniopassword"
  JWT_SECRET: "3JdrC5d9HauTsAb33spoS6EzSuGCtNS274rQ7V4B5pQ="
  MAIL_USERNAME: "seu_username_aqui"
  MAIL_PASSWORD: "sua_senha_aqui"